// generated by src/games/nethack/tools/nethack_gen.py
#ifndef NETHACK_NHDATA_H
#define NETHACK_NHDATA_H

#include <stddef.h>

typedef struct { const char *name; const unsigned char *data; unsigned int size; } tcm_nh_file_t;

extern const tcm_nh_file_t tcm_nh_files[];
extern const int tcm_nh_file_count;

#endif
