// generated by src/tools/image/tools/image_gen.py -- do not edit
#ifndef TCM_IMGDATA_H
#define TCM_IMGDATA_H

#include <stddef.h>

typedef struct { const char *name; const unsigned char *data; unsigned int size; } tcm_img_file_t;

extern const tcm_img_file_t tcm_img_files[];
extern const int tcm_img_file_count;

#endif
