#!/usr/bin/env python3
"""Embed NetHack runtime data files into nhdata.{h,cpp}."""
import os

DAT_DIR = "asset/nethack/dat"
OUT_H = "asset/nethack/nhdata.h"
OUT_CPP = "asset/nethack/nhdata.cpp"


def main():
    names = sorted(os.listdir(DAT_DIR))
    blobs = []
    for name in names:
        path = os.path.join(DAT_DIR, name)
        if not os.path.isfile(path):
            continue
        with open(path, "rb") as f:
            blobs.append((name, f.read()))

    total = sum(len(d) for _, d in blobs)
    with open(OUT_CPP, "w") as cpp, open(OUT_H, "w") as h:
        h.write("// generated by tools/nethack_gen.py\n")
        h.write("#ifndef NETHACK_NHDATA_H\n#define NETHACK_NHDATA_H\n\n")
        h.write("#include <stddef.h>\n\ntypedef struct { const char *name; const unsigned char *data; unsigned int size; } tcm_nh_file_t;\n\n")
        h.write("extern const tcm_nh_file_t tcm_nh_files[];\nextern const int tcm_nh_file_count;\n\n#endif\n")

        cpp.write("// generated by tools/nethack_gen.py -- do not edit\n")
        cpp.write("#include \"nhdata.h\"\n\n")
        for i, (name, data) in enumerate(blobs):
            sym = "nhfile_%d" % i
            cpp.write("static const unsigned char %s[] = {" % sym)
            for j in range(0, len(data), 20):
                cpp.write("\n" + "".join("%d," % b for b in data[j:j + 20]))
            cpp.write("};\n")
        cpp.write("\nconst tcm_nh_file_t tcm_nh_files[] = {\n")
        for i, (name, data) in enumerate(blobs):
            cpp.write("    {\"%s\", nhfile_%d, %u},\n" % (name, i, len(data)))
        cpp.write("};\n\nconst int tcm_nh_file_count = %d;\n" % len(blobs))
    print("embedded %d files, %d bytes" % (len(blobs), total))


if __name__ == "__main__":
    main()
