#!/usr/bin/env python3
"""Embed image/src/* into asset/images/imgdata.{h,cpp} (local tool)."""
import os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", ".."))
SRC = os.path.join(ROOT, "asset", "images", "src")
OUT_H = os.path.join(ROOT, "asset", "images", "imgdata.h")
OUT_CPP = os.path.join(ROOT, "asset", "images", "imgdata.cpp")


def main():
    names = sorted(
        n for n in os.listdir(SRC)
        if os.path.isfile(os.path.join(SRC, n)) and not n.startswith(".")
    )
    blobs = []
    for name in names:
        with open(os.path.join(SRC, name), "rb") as f:
            blobs.append((name, f.read()))
    total = sum(len(d) for _, d in blobs)

    with open(OUT_H, "w") as h:
        h.write("// generated by src/tools/image/tools/image_gen.py -- do not edit\n")
        h.write("#ifndef TCM_IMGDATA_H\n#define TCM_IMGDATA_H\n\n")
        h.write("#include <stddef.h>\n\n")
        h.write("typedef struct { const char *name; const unsigned char *data; "
                "unsigned int size; } tcm_img_file_t;\n\n")
        h.write("extern const tcm_img_file_t tcm_img_files[];\n")
        h.write("extern const int tcm_img_file_count;\n\n#endif\n")

    with open(OUT_CPP, "w") as cpp:
        cpp.write("// generated by src/tools/image/tools/image_gen.py -- do not edit\n")
        cpp.write('#include "imgdata.h"\n\n')
        for i, (name, data) in enumerate(blobs):
            cpp.write("static const unsigned char img_%d[] = {" % i)
            for j in range(0, len(data), 20):
                cpp.write("\n" + "".join("%d," % b for b in data[j:j + 20]))
            cpp.write("};\n")
        cpp.write("\nconst tcm_img_file_t tcm_img_files[] = {\n")
        for i, (name, data) in enumerate(blobs):
            cpp.write('    {"%s", img_%d, %u},\n' % (name, i, len(data)))
        cpp.write("};\n\nconst int tcm_img_file_count = %d;\n" % len(blobs))
    print("embedded %d files, %d bytes" % (len(blobs), total))


if __name__ == "__main__":
    main()
